language: node_js

node_js:
  - 10.15.3
services:
  - postgresql

before_script:
  - psql -c 'create database wayfarer;' -U wayfarer
  - psql -c "create user wayfarer WITH PASSWORD 'rrwcscrz1';" -U wayfarer
  
after_success: coveralls
