language: node_js

node_js:
  - 10.15.3
services:
  - postgresql

before_script:
  - cp config/database.yml.travis config/database.yml 
  - psql -c 'create database wayfarer;' -U postgres
  # - psql -c "create user wayfarer WITH PASSWORD 'rrwcscrz1';" -U postgres
  
after_success: coveralls
