language: node_js

node_js:
  - 10.15.3
services:
  - postgresql

before_script:
  - psql -c "create database wayfarer;" -U postgres
  - psql -c "create user wayfarer WITH PASSWORD 'rrwcscrz1';" -U postgres
  - "npm run create" 
after_success: coveralls
