language: node_js

node_js:
  - 10.15.3
services:
  - postgresql

before_script:
  - psql -c "create database wayfarer;" -U postgres
  - psql -c "create user wayfarer WITH PASSWORD 'rrwcscrz1';" -U postgres
  - "npm run dropall"
  - "npm run create"
  - "npm run bus"
  - "npm run trip"
after_success: 'npm run coverage'
